import plugin.GlobalSettings

plugins {
    id("java")
}

val globalSettings = gradle.extensions.findByType<GlobalSettings>()
    ?: error("plugin.GlobalSettings not initialized. Did you apply com.example.settings in settings.gradle.kts?")

group = rootProject.extra["maven_group"] as String
version = rootProject.extra["mod_version"] as String

// Modules to exclude from the merged jar
val excludedModules = listOf("processor", "runner")

allprojects {
    extensions.add<GlobalSettings>("globalSettings", globalSettings)
    plugins.apply("java-library")

    group = rootProject.group
    version = rootProject.version

    repositories {
        mavenCentral()
    }

    val targetJavaVersion = globalSettings.targetJavaVersion
    tasks.withType<JavaCompile> {
        options.encoding = "UTF-8"
        if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible) {
            options.release.set(targetJavaVersion)
        }
    }

    java {
        val javaVersion = JavaVersion.toVersion(targetJavaVersion)
        if (JavaVersion.current() < javaVersion) {
            toolchain.languageVersion.set(JavaLanguageVersion.of(targetJavaVersion))
        }

        if (globalSettings.sources) {
            withSourcesJar()
        }
    }
}

registerMergedJar("mergeJar", "jar")
if (globalSettings.sources) {
    registerMergedJar("mergeSourcesJar", "sourcesJar", "sources", true)
}

tasks.named("build") {
    dependsOn("mergeJar")
    if (globalSettings.sources) {
        dependsOn("mergeSourcesJar")
    }
}

// the name the access widener will be renamed to
val accessWidenerFileName = "${project.name}.accesswidener"

fun registerMergedJar(
    name: String,
    jarTaskName: String,
    classifier: String = "",
    sources: Boolean = false
) {
    // register task to merge subprojects together
    val mergeRaw = tasks.register<Jar>("${name}Raw") {
        description =
            "Merge all relevant subprojects into one jar and remove unnecessary files, output is not production ready"

        // move to temporary dir
        destinationDirectory.set(temporaryDir)
        archiveBaseName.set("${name}-raw")

        // allow duplicates because the final task will overwrite metadata files with the final correct variants
        duplicatesStrategy = DuplicatesStrategy.INCLUDE

        // gather all subprojects that should be merged
        val relevantProjects = subprojects.filter { !excludedModules.contains(it.name) }

        // depend on the relevant jar tasks
        val upstreamTasks = relevantProjects.mapNotNull { subproject ->
            subproject.tasks.findByName(jarTaskName)
        }.toMutableList()

        // if this is a sources jar, also explicitly depend on all relevant processResources tasks
        if (sources) {
            relevantProjects.forEach { subproject ->
                subproject.tasks.withType<ProcessResources>().findByName("processResources")?.let { task ->
                    upstreamTasks.add(task)
                }
            }
        }

        // declare the complete, explicit dependency graph to Gradle
        dependsOn(upstreamTasks)

        // include compiled classes OR sources + generated resources/sources
        from(relevantProjects.map { subproject ->
            val sourceSet = subproject.the<SourceSetContainer>()["main"]
            if (sources) {
                // grab sources
                val inputs = mutableListOf<Any>(sourceSet.allSource)

                // grab processed resources
                subproject.tasks.withType<ProcessResources>().findByName("processResources")?.let { task ->
                    inputs.add(task.destinationDir)
                }

                // grab files from generated source directories (f.e. for source files of classes generated by annotation processors)
                inputs.add(sourceSet.output.generatedSourcesDirs)

                // grab everything from classes output but exclude classes (f.e. for resources generated by annotation processors)
                inputs.add(sourceSet.output.classesDirs.elements.map { directories ->
                    directories.map { directory ->
                        subproject.fileTree(directory).matching {
                            exclude("**/*.class")
                        }
                    }
                })

                inputs
            } else {
                sourceSet.output
            }
        })

        // exclude mixin configuration index dir, as it is only relevant for development
        exclude("META-INF/mixins/**")

        // exclude .keep files
        exclude("**/.keep")

        // rename access widener to expected name and throw exception if more than one access widener is present
        var foundAccessWidener = false
        filesMatching("*.accesswidener") {
            if (!sources && foundAccessWidener) {
                throw GradleException("Multiple access wideners found in merged jar! Only one access widener is allowed.")
            }

            foundAccessWidener = true
            path = accessWidenerFileName
        }
    }

    // register task to make output of mergeRaw production ready by
    tasks.register<Jar>(name) {
        description = "Merges all modules together into one jar and cleans them up"
        archiveClassifier.set(classifier)

        // grab output of mergeRaw and create a tree from it
        val rawJarZipTree = mergeRaw.flatMap { it.archiveFile }.map { zipTree(it) }

        // get metadata task and get its output dir
        val metadataTask = tasks.named("processMergedJarMetadata")
        val metadataDirProvider = metadataTask.map { it.outputs.files.singleFile }

        // explicitly depend on the metadata task to build a solid execution graph
        dependsOn(metadataTask)

        // declare raw output as main input for the final jar
        from(rawJarZipTree) {
            // exclude raw fabric.mod.json as we want the cleaned up version
            exclude("fabric.mod.json")

            // lazily compute whether to remove the access widener
            val shouldRemoveAw by lazy {
                val flagFile = metadataDirProvider.get().resolve("remove_aw.txt")
                flagFile.exists() && flagFile.readText().toBoolean()
            }

            // loop through every file, if it's the access widener, and it should be removed, excludeit
            eachFile {
                if (this.name == accessWidenerFileName && shouldRemoveAw) {
                    this.exclude()
                }
            }
        }

        // include optimized fabric.mod.json from metadata processor
        from(metadataDirProvider) {
            include("fabric.mod.json")
        }
    }
}

tasks.register("processMergedJarMetadata") {
    description = "Process the fabric.mod.json and determine whether to delete the access widener"

    // lazily link to the raw binary jar output - establishes an absolute dependency graph
    val inputJarProvider = tasks.named<Jar>("mergeJarRaw").flatMap { it.archiveFile }
    val outputDirectory = temporaryDir.resolve("processed")

    inputs.file(inputJarProvider)
    outputs.dir(outputDirectory)

    doLast {
        val mixinFiles = mutableSetOf<String>()
        var removeAccessWidener = false
        var foundAccessWidener = false

        val jarTree = zipTree(inputJarProvider.get().asFile)

        // check if access widener is present & valid and gather the name of all mixin configurations
        jarTree.matching {
            include("*.mixins.json")
            include(accessWidenerFileName)
        }.visit {
            if (this.name == accessWidenerFileName) {
                foundAccessWidener = true
                removeAccessWidener = !isValidAccessWidener(this.open())
            } else if (this.name.endsWith(".mixins.json") && !this.isDirectory) {
                mixinFiles.add(this.relativePath.toString())
            }
        }

        // load and parse the fabric.mod.json
        val fabricModFile = jarTree.matching { include("fabric.mod.json") }.singleFile
        val fabricMod = groovy.json.JsonSlurper().parseText(fabricModFile.readText()) as Map<*, *>
        val fabricModMutable = fabricMod.toMutableMap()

        // get pre-launch entrypoints
        val entrypoints = (fabricMod["entrypoints"] as? Map<*, *>)?.toMutableMap() ?: mutableMapOf()
        val preLaunchEntrypoints = (entrypoints["preLaunch"] as? List<*>)?.toMutableList()

        if (preLaunchEntrypoints != null) {
            // if pre-launch entrypoints exist, remove mixin applier of the runner
            preLaunchEntrypoints.remove("modularmodtemplate.runner.DevEnvironmentMixinApplier::apply")

            if (preLaunchEntrypoints.isEmpty()) {
                // remove pre-launch entrypoint array if no pre-launch entrypoints are left
                entrypoints.remove("preLaunch")
            } else {
                // otherwise set remaining pre-launch entrypoints
                entrypoints["preLaunch"] = preLaunchEntrypoints
            }

            // apply modified entrypoints
            fabricModMutable["entrypoints"] = entrypoints
        }

        // add mixins if any exist
        if (mixinFiles.isNotEmpty()) {
            fabricModMutable["mixins"] = mixinFiles.toList()
        }

        // add access widener if it exists, otherwise remove the property (in case it was added manually)
        if (foundAccessWidener && !removeAccessWidener) {
            fabricModMutable["accessWidener"] = accessWidenerFileName
        } else {
            fabricModMutable.remove("accessWidener")
        }

        // write to output
        outputDirectory.mkdirs()
        outputDirectory.resolve("fabric.mod.json").writeText(
            groovy.json.JsonOutput.prettyPrint(groovy.json.JsonOutput.toJson(fabricModMutable))
        )
        outputDirectory.resolve("remove_aw.txt").writeText(removeAccessWidener.toString())
    }
}

fun isValidAccessWidener(stream: java.io.InputStream): Boolean {
    val bufferedReader = stream.bufferedReader(Charsets.UTF_8)
    bufferedReader.use { reader ->
        val header = reader.readLine()

        // if header is non-existent, or it doesn't start with accessWidener, the file isn't valid
        if (header == null || !header.startsWith("accessWidener ")) {
            return false
        }

        // if there is any line with content, mark as valid
        var line = reader.readLine()
        while (line != null) {
            if (line.trim().isNotEmpty()) {
                return true
            }

            line = reader.readLine()
        }
    }

    return false
}
