package modularmodtemplate.runner;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.spongepowered.asm.mixin.Mixins;

import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.List;
import java.util.jar.JarEntry;
import java.util.jar.JarFile;
import java.util.stream.Stream;

/**
 * Applies mixin configurations generated by the MixinAnnotationProcessor. Only needed in
 * development environments, as the configurations are added to the fabric.mod.json in production.
 */
@SuppressWarnings("unused")
public class DevEnvironmentMixinApplier {

  public static final Logger LOGGER = LoggerFactory.getLogger(DevEnvironmentMixinApplier.class);

  public void apply() {
    try {
      LOGGER.info("Looking for mixin configurations on the classpath...");
      List<Path> paths = this.listAllFilesFromResources(this, "META-INF/mixins/");
      if (paths.isEmpty()) {
        LOGGER.info("No mixin configurations found on the classpath");
        return;
      }

      LOGGER.info("Found {} mixin configurations on the classpath", paths.size());
      for (Path path : paths) {
        String name = path.getFileName().toString();
        LOGGER.info("Applying classpath mixin configuration {}", name);
        Mixins.addConfiguration(name);
      }
    } catch (URISyntaxException | IOException e) {
      throw new RuntimeException(e);
    }
  }

  private List<Path> listAllFilesFromResources(Object instance, String path)
      throws URISyntaxException, IOException {
    // Use getResources() to find all instances of the resource path on the classpath
    Enumeration<URL> dirURLs = instance.getClass().getClassLoader().getResources(path);

    List<Path> resources = new ArrayList<>();
    while (dirURLs.hasMoreElements()) {
      URL url = dirURLs.nextElement();
      if (url.getProtocol().equals("jar")) {
        url = URI.create(url.getPath()).toURL();
        String[] pathParts = url.getFile().split("!", 2);
        String jarPath = pathParts[0];
        String dirPath = pathParts.length > 1 ? pathParts[1].substring(1) : "";

        // if the resource url is a jar, open it
        try (JarFile jarFile = new JarFile(jarPath)) {
          Enumeration<JarEntry> entries = jarFile.entries();
          while (entries.hasMoreElements()) {
            JarEntry entry = entries.nextElement();
            String name = entry.getName();
            if (entry.isDirectory() || !name.startsWith(dirPath)) {
              continue;
            }

            String fileName = name.substring(dirPath.length());
            if (!fileName.isEmpty() && !fileName.contains("/")) {
              resources.add(Path.of(path, fileName));
            }
          }
        }
      } else if (url.getProtocol().equals("file")) {
        Path dirPath = Paths.get(url.toURI());

        // if the resource url is a file we can just loop through it
        try (Stream<Path> filesInDir = Files.list(dirPath)) {
          filesInDir.filter(Files::isRegularFile).forEach(resources::add);
        }
      }
    }

    return resources;
  }
}
