# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defense
# against bad commits.

name: build
on:
  push:
    branches: [ "master", "main" ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'microsoft'
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          validate-wrappers: true
          cache-read-only: ${{ github.ref != format('refs/heads/{0}', github.event.repository.default_branch) }}
      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew
      - name: Build with gradle
        run: ./gradlew build
      - name: Capture Build Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: Artifacts
          path: build/libs/